### ISSUE TITLE
Could you provide the paper link?

### ISSUE THREAD

**Issue by wait1988** [mkchoi-0323/modified_refinedet#1]
Nice work.Could you provide the paper link for more details?

**Comment by mkchoi-0323** [comment]
> Nice work.Could you provide the paper link for more details?

Thank you for your interest.

This work is still on the review. 
We have a double blind issue for fair review.
We will post the paper on arXiv no matter what the decision result on review.
It'll be ended at last day of may.
After revision, I'll add the link for the paper.

Thank you.

**Comment by wait1988** [comment]
@mkchoi-0323 Glad to know that.

**Comment by wait1988** [comment]
Any progress? @mkchoi-0323

**Comment by mkchoi-0323** [comment]
> Any progress? @mkchoi-0323

Sorry to late reply.
We upload our paper to arXiv.
Please refer updated README.
