### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by chen1234520** [mkchoi-0323/modified_refinedet#4]
we should use:    
python models/MobileNet/coco/refinedet_mobilenetv1_320x320/MobileNetV1_COCO_320.py

not:
python models/MobileNet/coco/refinedet_mobilenetv1_320x320/model_libs_MobileNetV1.py

**Comment by mkchoi-0323** [comment]
> we should use:
> python models/MobileNet/coco/refinedet_mobilenetv1_320x320/MobileNetV1_COCO_320.py
> 
> not:
> python models/MobileNet/coco/refinedet_mobilenetv1_320x320/model_libs_MobileNetV1.py

Thank you for pointing out. I fixed that part.
